import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '3.3.0:0',
  releaseNotes: {
    en_US:
      'Paperless-ngx 3.3.0.\n\n**This update cannot be rolled back.** The first start migrates the database and rebuilds the search index, which can take a while. Back up Paperless-ngx before updating.\n\n- Duplicate documents are imported and flagged as duplicates.\n- Only documents that needed OCR get a separate archived copy. To get one for every document, set **Archive File Generation** to **Always** under **Configuration**.\n- Notes and custom fields are searched with the `notes.note:` and `custom_fields.value:` prefixes. Update any saved view that relies on a plain search term to find them.\n- Task history is cleared.\n- On x86_64, Paperless-ngx requires a CPU with SSE4.2.\n\nNew **Set Consume Folder** action: Paperless-ngx can watch a folder in FileBrowser Quantum, so documents dropped there are imported automatically.\n\n- Set Admin Password asks for confirmation before it replaces an existing password, and says that the current password stops working.\n- The Consume Folder field of Set Consume Folder explains each option.',
    es_ES:
      'Paperless-ngx 3.3.0.\n\n**Esta actualización no se puede revertir.** El primer inicio migra la base de datos y reconstruye el índice de búsqueda, lo que puede tardar un rato. Haz una copia de seguridad de Paperless-ngx antes de actualizar.\n\n- Los documentos duplicados se importan y se marcan como duplicados.\n- Solo los documentos que necesitaron OCR obtienen una copia archivada aparte. Para obtenerla en todos los documentos, establece **Archive File Generation** en **Always** en **Configuration**.\n- Las notas y los campos personalizados se buscan con los prefijos `notes.note:` y `custom_fields.value:`. Actualiza cualquier vista guardada que dependa de un término de búsqueda simple para encontrarlos.\n- El historial de tareas se borra.\n- En x86_64, Paperless-ngx requiere una CPU con SSE4.2.\n\nNueva acción **Establecer carpeta de consumo**: Paperless-ngx puede vigilar una carpeta de FileBrowser Quantum, de modo que los documentos que se dejen allí se importen automáticamente.\n\n- Establecer contraseña de administrador pide confirmación antes de reemplazar una contraseña existente e indica que la contraseña actual deja de funcionar.\n- El campo Carpeta de consumo de Establecer carpeta de consumo explica cada opción.',
    de_DE:
      'Paperless-ngx 3.3.0.\n\n**Dieses Update kann nicht rückgängig gemacht werden.** Der erste Start migriert die Datenbank und baut den Suchindex neu auf, was eine Weile dauern kann. Sichere Paperless-ngx vor dem Update.\n\n- Doppelte Dokumente werden importiert und als Duplikate markiert.\n- Nur Dokumente, die OCR benötigt haben, erhalten eine separate archivierte Kopie. Um eine für jedes Dokument zu erhalten, setze **Archive File Generation** unter **Configuration** auf **Always**.\n- Notizen und benutzerdefinierte Felder werden mit den Präfixen `notes.note:` und `custom_fields.value:` durchsucht. Passe gespeicherte Ansichten an, die sie über einen einfachen Suchbegriff finden.\n- Der Aufgabenverlauf wird geleert.\n- Auf x86_64 benötigt Paperless-ngx eine CPU mit SSE4.2.\n\nNeue Aktion **Konsum-Ordner festlegen**: Paperless-ngx kann einen Ordner in FileBrowser Quantum überwachen, sodass dort abgelegte Dokumente automatisch importiert werden.\n\n- Admin-Passwort festlegen fragt vor dem Ersetzen eines vorhandenen Passworts nach einer Bestätigung und weist darauf hin, dass das aktuelle Passwort nicht mehr funktioniert.\n- Das Feld Konsum-Ordner von Konsum-Ordner festlegen erklärt jede Option.',
    pl_PL:
      'Paperless-ngx 3.3.0.\n\n**Tej aktualizacji nie można cofnąć.** Pierwsze uruchomienie migruje bazę danych i odbudowuje indeks wyszukiwania, co może chwilę potrwać. Przed aktualizacją wykonaj kopię zapasową Paperless-ngx.\n\n- Zduplikowane dokumenty są importowane i oznaczane jako duplikaty.\n- Osobną zarchiwizowaną kopię otrzymują tylko dokumenty, które wymagały OCR. Aby otrzymać ją dla każdego dokumentu, ustaw **Archive File Generation** na **Always** w sekcji **Configuration**.\n- Notatki i pola niestandardowe przeszukuje się z prefiksami `notes.note:` i `custom_fields.value:`. Zaktualizuj zapisane widoki, które znajdują je za pomocą zwykłego wyszukiwanego słowa.\n- Historia zadań zostaje wyczyszczona.\n- Na x86_64 Paperless-ngx wymaga procesora z SSE4.2.\n\nNowa akcja **Ustaw folder konsumpcji**: Paperless-ngx może obserwować folder w FileBrowser Quantum, dzięki czemu umieszczone tam dokumenty są importowane automatycznie.\n\n- Ustaw hasło administratora prosi o potwierdzenie przed zastąpieniem istniejącego hasła i informuje, że obecne hasło przestaje działać.\n- Pole Folder konsumpcji w akcji Ustaw folder konsumpcji objaśnia każdą opcję.',
    fr_FR:
      "Paperless-ngx 3.3.0.\n\n**Cette mise à jour ne peut pas être annulée.** Le premier démarrage migre la base de données et reconstruit l'index de recherche, ce qui peut prendre un moment. Sauvegardez Paperless-ngx avant la mise à jour.\n\n- Les documents en double sont importés et signalés comme doublons.\n- Seuls les documents qui ont nécessité l'OCR reçoivent une copie archivée distincte. Pour en obtenir une pour chaque document, réglez **Archive File Generation** sur **Always** dans **Configuration**.\n- Les notes et les champs personnalisés se recherchent avec les préfixes `notes.note:` et `custom_fields.value:`. Mettez à jour toute vue enregistrée qui compte sur un terme de recherche simple pour les trouver.\n- L'historique des tâches est effacé.\n- Sur x86_64, Paperless-ngx nécessite un processeur avec SSE4.2.\n\nNouvelle action **Définir le dossier de consommation** : Paperless-ngx peut surveiller un dossier de FileBrowser Quantum, afin que les documents qui y sont déposés soient importés automatiquement.\n\n- Définir le mot de passe admin demande une confirmation avant de remplacer un mot de passe existant, et indique que le mot de passe actuel cesse de fonctionner.\n- Le champ Dossier de consommation de Définir le dossier de consommation explique chaque option.",
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
